export const Planets = [
  {
    name: "Mercury",
    color: "tan",
    size: 2.439,
    distanceFromSun: 57.91,
    orbitalVelocity: 1.607,
  },
  {
    name: "Earth",
    color: "lightskyblue",
    size: 6.371,
    distanceFromSun: 149.6,
    orbitalVelocity: 1.0,
  },
  {
    name: "Saturn",
    color: "papayawhip",
    size: 58.232,
    distanceFromSun: 1434,
    orbitalVelocity: 0.323,
  },
  {
    name: "Mars",
    color: "firebrick",
    size: 3.389,
    distanceFromSun: 227.9,
    orbitalVelocity: 0.802,
  },
  {
    name: "Neptune",
    color: "rebeccapurple",
    size: 24.622,
    distanceFromSun: 4495,
    orbitalVelocity: 0.182,
  },
  {
    name: "Jupiter",
    color: "coral",
    size: 69.911,
    distanceFromSun: 778.5,
    orbitalVelocity: 0.434,
  },
  {
    name: "Venus",
    color: "hotpink",
    size: 6.051,
    distanceFromSun: 108.2,
    orbitalVelocity: 1.174,
  },
  {
    name: "Uranus",
    color: "mediumslateblue",
    size: 25.362,
    distanceFromSun: 2871,
    orbitalVelocity: 0.228,
  },
];
